/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Location API
 * API for searching and finding Capitec branch locations.
Supports searching by area text (city, suburb, postal code, etc.) or by geographic coordinates.

 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { axiosJSONContentDefaultInstanceWrapper } from '../../lib/axios/default-axios';
/**
 * Response containing branches matching the search criteria
 */
export interface BranchSearchResponse {
  /** List of branches matching the search */
  branches: BranchLocation[];
  /** Total number of matching branches */
  totalCount: number;
}

/**
 * Response containing nearest branches to the given coordinates
 */
export interface NearbyBranchesResponse {
  /** List of nearby branches sorted by distance */
  branches: BranchLocation[];
  /** Total number of branches returned */
  totalCount: number;
}

/**
 * Branch operation times keyed by date (ISO format YYYY-MM-DD)
 */
export type BranchLocationOperationTimes = {[key: string]: OperationTime};

/**
 * Detailed information about a Capitec branch location
 */
export interface BranchLocation {
  /** Unique identifier of the branch */
  branchId: string;
  /**
   * Branch code
   * @nullable
   */
  branchCode?: string | null;
  /** Name of the branch */
  name: string;
  /** Complete address of the branch */
  fullAddress: string;
  /** Latitude coordinate of the branch */
  latitude: number;
  /** Longitude coordinate of the branch */
  longitude: number;
  /** Distance from the search coordinates in kilometers (0 for area search) */
  distanceKm: number;
  /** Branch operation times keyed by date (ISO format YYYY-MM-DD) */
  operationTimes: BranchLocationOperationTimes;
  /** Indicates if the branch is a business banking center */
  businessBankCenter: boolean;
  /** Indicates if the result was fetched from cached nearby location data
(only true when service fallback was used)
 */
  fromNearbyLocation: boolean;
}

/**
 * Branch operation hours for a specific day
 */
export interface OperationTime {
  /**
   * Opening time (HH:mm format)
   * @nullable
   */
  openAt: string | null;
  /**
   * Closing time (HH:mm format)
   * @nullable
   */
  closeAt: string | null;
  /** Whether the branch is closed on this day */
  closed: boolean;
  /** Whether this day is a holiday */
  isHoliday: boolean;
}

/**
 * Standard error response
 */
export interface ErrorResponse {
  /** Time when the error occurred */
  timestamp: string;
  /** HTTP status code */
  status: number;
  /** HTTP error type */
  error: string;
  /** Human-readable error message */
  message: string;
  /** Request path that caused the error */
  path: string;
  /** Trace ID for error tracking */
  traceId?: string;
}

/**
 * Unique trace identifier for request tracking
 */
export type TraceIdParameter = string;

export type SearchBranchesByAreaParams = {
/**
 * Search text (city, suburb, postal code, branch name, etc.)
 * @minLength 2
 * @maxLength 100
 */
q: string;
};

export type FindNearestBranchesParams = {
/**
 * Latitude of the customer's location
 * @minimum -90
 * @maximum 90
 */
latitude: number;
/**
 * Longitude of the customer's location
 * @minimum -180
 * @maximum 180
 */
longitude: number;
/**
 * Maximum number of branches to return (default 10)
 * @minimum 1
 * @maximum 50
 */
limit?: number;
/**
 * Maximum distance in kilometers to search for branches
 * @minimum 1
 * @maximum 500
 */
maxDistanceKm?: number;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Search for Capitec branches by area text input.
Searches across city, province, suburb, address, postal code, and branch name.
Only returns branches available for appointment booking (excludes ATMs and closed branches).

 * @summary Search branches by area
 */
export const searchBranchesByArea = (
    params: SearchBranchesByAreaParams,
 options?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>,signal?: AbortSignal
) => {
      
      
      return axiosJSONContentDefaultInstanceWrapper<BranchSearchResponse>(
      {url: `/branches/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchBranchesByAreaQueryKey = (params?: SearchBranchesByAreaParams,) => {
    return [
    `/branches/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchBranchesByAreaQueryOptions = <TData = Awaited<ReturnType<typeof searchBranchesByArea>>, TError = ErrorResponse>(params: SearchBranchesByAreaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBranchesByArea>>, TError, TData>>, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchBranchesByAreaQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchBranchesByArea>>> = ({ signal }) => searchBranchesByArea(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchBranchesByArea>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchBranchesByAreaQueryResult = NonNullable<Awaited<ReturnType<typeof searchBranchesByArea>>>
export type SearchBranchesByAreaQueryError = ErrorResponse


export function useSearchBranchesByArea<TData = Awaited<ReturnType<typeof searchBranchesByArea>>, TError = ErrorResponse>(
 params: SearchBranchesByAreaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBranchesByArea>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchBranchesByArea>>,
          TError,
          Awaited<ReturnType<typeof searchBranchesByArea>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchBranchesByArea<TData = Awaited<ReturnType<typeof searchBranchesByArea>>, TError = ErrorResponse>(
 params: SearchBranchesByAreaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBranchesByArea>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchBranchesByArea>>,
          TError,
          Awaited<ReturnType<typeof searchBranchesByArea>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchBranchesByArea<TData = Awaited<ReturnType<typeof searchBranchesByArea>>, TError = ErrorResponse>(
 params: SearchBranchesByAreaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBranchesByArea>>, TError, TData>>, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search branches by area
 */

export function useSearchBranchesByArea<TData = Awaited<ReturnType<typeof searchBranchesByArea>>, TError = ErrorResponse>(
 params: SearchBranchesByAreaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBranchesByArea>>, TError, TData>>, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchBranchesByAreaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Find the nearest Capitec branches to a given geographic location.
Returns branches sorted by distance from the provided coordinates.
Only returns branches available for appointment booking (excludes ATMs and closed branches).

When the branch locator service is unavailable, cached data from nearby locations 
(within 5km radius) may be returned. The `fromNearbyLocation` flag indicates if 
the response is from cached nearby data.

 * @summary Find nearest branches by coordinates
 */
export const findNearestBranches = (
    params: FindNearestBranchesParams,
 options?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>,signal?: AbortSignal
) => {
      
      
      return axiosJSONContentDefaultInstanceWrapper<NearbyBranchesResponse>(
      {url: `/branches/nearby`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getFindNearestBranchesQueryKey = (params?: FindNearestBranchesParams,) => {
    return [
    `/branches/nearby`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFindNearestBranchesQueryOptions = <TData = Awaited<ReturnType<typeof findNearestBranches>>, TError = ErrorResponse>(params: FindNearestBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findNearestBranches>>, TError, TData>>, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindNearestBranchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findNearestBranches>>> = ({ signal }) => findNearestBranches(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findNearestBranches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindNearestBranchesQueryResult = NonNullable<Awaited<ReturnType<typeof findNearestBranches>>>
export type FindNearestBranchesQueryError = ErrorResponse


export function useFindNearestBranches<TData = Awaited<ReturnType<typeof findNearestBranches>>, TError = ErrorResponse>(
 params: FindNearestBranchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findNearestBranches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findNearestBranches>>,
          TError,
          Awaited<ReturnType<typeof findNearestBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindNearestBranches<TData = Awaited<ReturnType<typeof findNearestBranches>>, TError = ErrorResponse>(
 params: FindNearestBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findNearestBranches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findNearestBranches>>,
          TError,
          Awaited<ReturnType<typeof findNearestBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindNearestBranches<TData = Awaited<ReturnType<typeof findNearestBranches>>, TError = ErrorResponse>(
 params: FindNearestBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findNearestBranches>>, TError, TData>>, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find nearest branches by coordinates
 */

export function useFindNearestBranches<TData = Awaited<ReturnType<typeof findNearestBranches>>, TError = ErrorResponse>(
 params: FindNearestBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findNearestBranches>>, TError, TData>>, request?: SecondParameter<typeof axiosJSONContentDefaultInstanceWrapper>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindNearestBranchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
